//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.DistentClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class langage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.DistentClient.Resources.langage", typeof(langage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string allFiles {
            get {
                return ResourceManager.GetString("allFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompSelect {
            get {
                return ResourceManager.GetString("CompSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control pannel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new SaveWork.
        /// </summary>
        public static string CreateSaveWork {
            get {
                return ResourceManager.GetString("CreateSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected SaveWork.
        /// </summary>
        public static string deleteSelectedSaveWork {
            get {
                return ResourceManager.GetString("deleteSelectedSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string diffSelect {
            get {
                return ResourceManager.GetString("diffSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty or already existing..
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path is not valid..
        /// </summary>
        public static string ErrorPathDest {
            get {
                return ResourceManager.GetString("ErrorPathDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path is not valid..
        /// </summary>
        public static string ErrorPathSource {
            get {
                return ResourceManager.GetString("ErrorPathSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new key.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string launch {
            get {
                return ResourceManager.GetString("launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of the application is already running..
        /// </summary>
        public static string MonoInstance {
            get {
                return ResourceManager.GetString("MonoInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string nameInput {
            get {
                return ResourceManager.GetString("nameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveWork control panel.
        /// </summary>
        public static string namePopUp {
            get {
                return ResourceManager.GetString("namePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Path :.
        /// </summary>
        public static string pathFromInput {
            get {
                return ResourceManager.GetString("pathFromInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Path :.
        /// </summary>
        public static string pathToInput {
            get {
                return ResourceManager.GetString("pathToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause selected SaveWork.
        /// </summary>
        public static string pauseSelectedSaveWork {
            get {
                return ResourceManager.GetString("pauseSelectedSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play selected SaveWork.
        /// </summary>
        public static string playSelectedSaveWork {
            get {
                return ResourceManager.GetString("playSelectedSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop selected SaveWork.
        /// </summary>
        public static string stopSelectedSaveWork {
            get {
                return ResourceManager.GetString("stopSelectedSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string tabDelete {
            get {
                return ResourceManager.GetString("tabDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string tabModification {
            get {
                return ResourceManager.GetString("tabModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string tabName {
            get {
                return ResourceManager.GetString("tabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path from.
        /// </summary>
        public static string tabPathFrom {
            get {
                return ResourceManager.GetString("tabPathFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to.
        /// </summary>
        public static string tabPathTo {
            get {
                return ResourceManager.GetString("tabPathTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string tabPause {
            get {
                return ResourceManager.GetString("tabPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or resume.
        /// </summary>
        public static string tabPlay {
            get {
                return ResourceManager.GetString("tabPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar.
        /// </summary>
        public static string tabProgressBar {
            get {
                return ResourceManager.GetString("tabProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress state.
        /// </summary>
        public static string tabProgressState {
            get {
                return ResourceManager.GetString("tabProgressState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop .
        /// </summary>
        public static string tabStop {
            get {
                return ResourceManager.GetString("tabStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string tabType {
            get {
                return ResourceManager.GetString("tabType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string typeInput {
            get {
                return ResourceManager.GetString("typeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
